### PR TITLE
connecte with email or nickname and fix bug

### PR DESCRIPTION
**Pull request by simon511000**
possibility to connect with his email address or his nickname

### CODE REVIEW

**Comment by mitchellurgero** [comment]
how tested is this?

**Comment by simon511000** [comment]
It’s work, I have tested ^^

if (i’m connect with simon511000)
{
    it’s work
}
if (i’m connect with simon@simon511000.fr)
{
    it’s work too
}

**Comment by simon511000** [comment]
and :

**Comment by mitchellurgero** [comment]
Alright code looks good. Merged.

**Comment by mitchellurgero** [comment]
Actually this broke login for me, I am going to revert it and implement myself.

**Pull request merged**
